#配置环境
spring:
  devtools:
    livereload:
      port: 30980
      enabled: true
  profiles:
    active: prd


  #配置视图解析器
  mvc:
    view:
      prefix:
      suffix: .html

  #配置数据源
  datasource:
    username: root
    password: '#Zbq123456'
    url: jdbc:mysql://localhost:3306/users?useUnicode=true&;characterEncoding=UTF-8&;useSSL=true&;serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #Hikari连接池的设置
    hikari:
      minimum-idle: 5 #最小连接
      maximum-pool-size: 30 #最大连接
      auto-commit: false #自动提交
      idle-timeout: 30000 #最大空闲时长(30秒)
      pool-name: DatebookHikariCP #连接池名
      max-lifetime: 900000 #最大生命周期
      connection-timeout: 4500 #连接超时时间
      connection-test-query: SELECT 1 #心跳检测


#配置服务器端口号
server:
  port: 8081
  servlet:
    #配置访问前缀
    context-path: /province

# 数据库授权
#  grant all on *.* to admin@'%' identified by 'sunben';
logging:
  config: classpath:logback-spring.xml



#配置mybatis
mybatis:
  #配置映射文件路径
  mapper-locations: classpath:mapping/*.xml
  #配置实体类别名，就是dao层操作所需传入或输出的对象类前缀，简化书写
  type-aliases-package: com.province.survey.entity